# Generated by Django 3.1 on 2024-01-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_News_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_days', models.CharField(max_length=100)),
                ('mass_date', models.DateField()),
                ('mass_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mass_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Details_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('organizer', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('time', models.TimeField()),
                ('end_date', models.DateTimeField()),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('event_description', models.CharField(max_length=1000)),
                ('description_image', models.ImageField(upload_to='images/')),
                ('event_venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('event_gallery_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MinistriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_times', models.ImageField(upload_to='images/')),
                ('ask_for_prayer', models.ImageField(upload_to='images/')),
                ('obitury', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Obituary_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Special_Masses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('gallery_images', models.ManyToManyField(to='newapp.GalleryImage')),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='gallery_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.gallerymodel'),
        ),
        migrations.CreateModel(
            name='Event_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.event_details_model')),
            ],
        ),
    ]
