# Generated by Django 3.1 on 2024-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('organizer', models.CharField(max_length=100)),
                ('notification_start_date', models.DateField()),
                ('notification_end_date', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('time', models.TimeField()),
                ('end_date', models.DateTimeField()),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('event_description', models.CharField(max_length=1000)),
                ('description_image', models.ImageField(upload_to='images/')),
                ('event_venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('event_gallery_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
