# Generated by Django 3.1 on 2024-01-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_event_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='event_name',
        ),
        migrations.DeleteModel(
            name='Event_Details_Model',
        ),
        migrations.DeleteModel(
            name='Event_Registration',
        ),
    ]
