# Generated by Django 3.1 on 2024-01-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20240121_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Details',
            new_name='Event_Details_Model',
        ),
    ]
