# Generated by Django 3.1 on 2024-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20240121_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details_model',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
