# Generated by Django 3.1 on 2024-01-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20240121_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='gallery_images',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='GalleryModel',
        ),
    ]
