# Generated by Django 3.1 on 2024-01-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20240124_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details_model',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
