# Generated by Django 3.1 on 2024-01-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20240126_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='gallery_name',
            field=models.CharField(max_length=100),
        ),
    ]
