# Generated by Django 3.1 on 2024-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_auto_20240130_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('privilege', models.CharField(choices=[('St.VincentDePaulSociety', 'St.VincentDePaulSociety'), ('StarsPithruvedi', 'StarsPithruvedi'), ('MathruJyothi', 'MathruJyothi'), ('STYF', 'STYF'), ('AltarServants', 'AltarServants'), ('BibleReadersForum', 'BibleReadersForum'), ('Choir', 'Choir'), ('CML', 'CML'), ('HolyChildhood', 'HolyChildhood')], max_length=80)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
