# Generated by Django 3.1 on 2024-02-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_userregistermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
