# Generated by Django 3.1 on 2024-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_stars_pithruvedi_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mathrujyothi_Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(blank=True, max_length=500, null=True)),
                ('objectives', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
