# Generated by Django 3.1 on 2024-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_mathrujyothi_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styf_Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('member_name', models.CharField(blank=True, max_length=20, null=True)),
                ('member_designation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
