# Generated by Django 3.1 on 2024-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_auditorium_booking_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='styf_association',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
