# Generated by Django 3.1 on 2024-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_styf_association_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details_model',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
