# Generated by Django 3.1 on 2024-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_daily_mass_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
