# Generated by Django 3.1 on 2024-02-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_userregistermodel_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('news_heading', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='News_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='0-default,1-Hidden')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.news_category')),
            ],
        ),
    ]
